export Timelapse_ConnectionStrings__DefaultConnection="Host=timelapse.postgres.database.azure.com;Port=5432;User ID=postgres;Password=<SUPER_SECRET_PASSWORD>;Database=timelapse"
export TimelapseDev_ConnectionStrings__DefaultConnection="Host=timelapse.postgres.database.azure.com;Port=5432;User ID=postgres;Password=<SUPER_SECRET_PASSWORD>;Database=timelapse-dev"
export Timelapse_DBadmin_user="postgres"
export Timelapse_DBadmin_password="<SUPER_SECRET_PASSWORD>"
export SendgridAPIKey="<SUPER_SECRET_PASSWORD>"
export ThirdParty_ApiKey="<SUPER_SECRET_PASSWORD>"
export LINZApiKey="<SUPER_SECRET_API_KEY>"