export Timelapse_ConnectionStrings__DefaultConnection="Host=timelapse.postgres.database.azure.com;Port=5432;User ID=postgres;Password=<SUPER SECRET PASSWORD>;Database=timelapse"
export TimelapseDev_ConnectionStrings__DefaultConnection="Host=timelapse.postgres.database.azure.com;Port=5432;User ID=postgres;Password=<SUPER SECRET PASSWORD>;Database=timelapse-dev;Include Error Detail=true"
export Timelapse_DBadmin_user="postgres"
export Timelapse_DBadmin_password="<SUPER SECRET PASSWORD>"
export SendgridAPIKey="<SUPER SECRET PASSWORD>"
export SendgridFromAddress="enviroeyes@<yurdomain>"
export ThirdParty_ApiKey="<SUPER SECRET PASSWORD>"
export LINZApiKey="<SUPER SECRET API KEY>"