version: "2.1"

services:
  wifi-connect:
    image: balenablocks/wifi-connect:aarch64
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"


  pijuice:
    build: ./pijuice
    privileged: true
    labels: 
      io.balena.features.balena-api: '1'
      
  sample:
    build: ./sample